### ISSUE TITLE
Screen Not Centered

### ISSUE THREAD

**Issue by Santange11** [dominicklee/3D-Print-Bed-Leveler#1]
Hello,

I have followed your instructions and uploaded the firmware as is to the M5StickC, but it is only showing one quarter of the screen. Is there something I need to adjust in the firmware to get the screen to display properly?

**Comment by dominicklee** [comment]
Thanks for using the firmware! I believe you might have the newer M5StickC Plus. The code was written for the original M5 Stick. However, you are welcome to adjust the positions in the firmware to align them for you newer M5StickC Plus. You might have to play around with the coordinates to get the interface realigned.

We may roll out a new firmware version in the future that supports the M5StickC Plus.
